#!/bin/bash
# 部署脚本 - 在终端运行

echo "=== 迪哥精准营养网站部署 ==="
echo ""
echo "请在终端运行以下命令："
echo ""
echo "1. 创建GitHub仓库（手动）："
echo "   - 访问 https://github.com/new"
echo "   - Repository name: dige-precision-nutrition"
echo "   - 选择 Public"
echo "   - 不要勾选 Add a README file"
echo "   - 点击 Create repository"
echo ""
echo "2. 推送代码到GitHub："
echo "   cd ~/.openclaw/workspace/dige-precision-nutrition"
echo '   git remote add origin https://github.com/dige2020/dige-precision-nutrition.git'
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. 启用GitHub Pages："
echo "   - 仓库设置 → Pages"
echo "   - Source: Deploy from a branch"
echo "   - Branch: main"
echo "   - 保存"
echo ""
echo "4. 等待1-2分钟，访问："
echo "   https://dige2020.github.io/dige-precision-nutrition/"
echo ""
